### ISSUE TITLE
What is "fetching as little as needed"?

### ISSUE THREAD

**Issue by farski** [gottfrois/image_info#1]
From what I can tell this just seems to make normal requests for any image file. Are there cases where the gem doesn't download the entire image file to determine the size, or am I misunderstanding what "as little as needed" is referring to?

**Comment by gottfrois** [comment]
You are right, in its current state, the gem download the entire image in order to get its size. I have plan to use Typhoeus stream capability to stop downloading the image as soon as its metadata can be computed.

**Comment by vdaubry** [comment]
Great job with this gem, i wanted to develop something similar to improve performance of [FastImage](https://github.com/sdsykes/fastimage) gem.

Would you consider a PR for this feature ?

I was thinking of modifying `ImageInfo::RequestHandler` to get the image stream from Typhoeus.
Then mimic the method [parse_type](https://github.com/sdsykes/fastimage/blob/master/lib/fastimage.rb#L401) and methods to get image size corresponding to each image type.

What do you think ?

**Comment by gottfrois** [comment]
Sure a PR is always welcome.

Currently I use the [image_size](https://github.com/toy/image_size) gem as a dependency to get image type and size. I believe it's possible to send that gem a partial image (from typhoeus stream) to get a response. We should start looking at this before thinking of implementing our own algorithm.

**Comment by vdaubry** [comment]
Yep good idea.

**Comment by vdaubry** [comment]
Some update : i did some quick tests and image_size can compute size from a StringIO containing a partial image.

But i didn't manage to abort a request from Typhoeus, which would make all of this pointless. I opened an issue on Typhoeus, did you already manage to cancel a currently running request ?

https://github.com/typhoeus/typhoeus/issues/466

**Comment by gottfrois** [comment]
yes you actually only need to change this code https://github.com/gottfrois/image_info/blob/master/lib/image_info/request_handler.rb#L18

into something like:

``` ruby
def on_body(data)
  return :abort if some_condition

  #process stream
end
```

**Comment by vdaubry** [comment]
I opened an issue on typhoeus because returning `:abort` doesn't cancel the request :

https://github.com/typhoeus/typhoeus/issues/466

**Comment by gottfrois** [comment]
Oh really? I had the feeling it worked when I played around with it. Maybe this link can help you/them https://github.com/typhoeus/ethon/commit/6117872004c9ed1dac0ac15542dffc10177d8eae

Thanks for looking at this by the way ;)

**Comment by vdaubry** [comment]
@gottfrois : Good news, @i0rek fixed the abort issue on typhoeus

There is a branch that allows to abort a download : https://github.com/typhoeus/typhoeus/pull/468

I'll try to provide a PR for image_info with this as soon as it's merged.
