### ISSUE TITLE
Warning: URI.escape is obsolete (Ruby 2.7.0)

### ISSUE THREAD

**Issue by iamladi** [gottfrois/image_info#7]
Apparent URI.escape is obsolete in Ruby 2.7.0, so the following warning is shown whenever running rails console.

`vendor/bundle/ruby/2.7.0/gems/image_info-1.2.0/lib/image_info/image.rb:10: warning: URI.escape is obsolete`

Here's a similar ticket on a different project: https://github.com/contentful/contentful.rb/pull/221/files

**Comment by gottfrois** [comment]
Hey @martincik, thank you for reporting this, I will take a look.
